### ISSUE TITLE
Problem with ActiveAdmin.resources

### ISSUE THREAD

**Issue by spiegela** [vigetlabs/active_admin_associations#8]
I have a new application I'm trying to implement aa_associations with, an on my first, try I'm getting an error when using the form_associations.

It appears the active_admin extension that aa_associations uses to get a list of all the resources isn't working with my version of aa (0.5.0)

It get the following error:

``` ruby
undefined method `resource_class' for #<ActiveAdmin::Page:0x007fc4c5d42ec0>
```

this is coming from the active_admin_extensions.rb here:

``` ruby
    def resources
      application.namespaces.values.map{|n| n.resources.resources }.flatten.compact.map(&:resource_class)
    end
```

Apparently, that mapping now includes ActiveAdmin::Page for some reason -- I'm not sure, but that looks like the intent is just to find the models for which ActiveAdmin is configured.

Backtrace:
  https://gist.github.com/4009607

**Comment by dmahlow** [comment]
Here is a workaround:
https://github.com/dmahlow/active_admin_associations/commit/931b4c13cfb199a8a705eb69944adad3288b4299

Since I haven't investigated what exactly changed in active_admin, I'm not issuing a pull request, but it does work.

**Comment by maxstudener** [comment]
+1 still an issue

**Comment by brianjlandau** [comment]
Fixed and released
